name: HidePlayers
version: 0.2
author: LaxWasHere
main: net.lazlecraft.hideplayers.HidePlayers
commands:
    hideplayers:
        description: Hide people from your view.
        aliases: hideppl
        permission: hide.people
        permission-message: You may not!
    showplayers:
        description: Hide people from your view.
        aliases: showppl
        permission: show.people
        permission-message: You may not!